version: "3.8"

networks:
  dev:
    driver: bridge
    name: dev

volumes:
  gems:
    name: gems

services:

  ruby: 
    image: ruby:2.7.5-buster
    working_dir: /app
    networks:
      - dev
    volumes:
      - gems:/gems
      - ./src/jekyll:/app
      - ./dist:/dist
    environment:
      GEM_HOME: /gems

  node:
    image: node:16.13.0-buster
    working_dir: /app
    networks:
      - dev
    volumes:
      - ./:/app
